const city = [
    { CityName: "Aberdeen	        ", code: "ABZ", airportName: "Dyce	                           ", country: "United Kingdom", },
    { CityName: "Abingdon	        ", code: "ABB", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "Alderney	        ", code: "ACI", airportName: "The Blaye	                      ", country: "United Kingdom", },
    { CityName: "Bally Kelly	     ", code: "BOL", airportName: "Bally Kelly	                    ", country: "United Kingdom", },
    { CityName: "Barra	           ", code: "BRR", airportName: "North Bay	                      ", country: "United Kingdom", },
    { CityName: "Barrow-In-Furness", code: "BWF", airportName: "Walney Island	                  ", country: "United Kingdom", },
    { CityName: "Belfast	         ", code: "BHD", airportName: "Belfast City Airport	           ", country: "United Kingdom", },
    { CityName: "Belfast	         ", code: "BFS", airportName: "Belfast Aldergrove International", country: "United Kingdom", },
    { CityName: "Bembridge	       ", code: "BBP", airportName: "Bembridge	                      ", country: "United Kingdom", },
    { CityName: "Benbecula	       ", code: "BEB", airportName: "Benbecula	                      ", country: "United Kingdom", },
    { CityName: "Benson	          ", code: "BEX", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "Birmingham	      ", code: "BHX", airportName: "Birmingham International	       ", country: "United Kingdom", },
    { CityName: "Yateley	         ", code: "BBS", airportName: "Blackbushe	                     ", country: "United Kingdom", },
    { CityName: "Blackpool	       ", code: "BLK", airportName: "Blackpool	                      ", country: "United Kingdom", },
    { CityName: "Bournemouth	     ", code: "BOH", airportName: "Bournemouth International	      ", country: "United Kingdom", },
    { CityName: "Braintree	       ", code: "WXF", airportName: "Wether Fld RAF	                 ", country: "United Kingdom", },
    { CityName: "Brandon	         ", code: "LKZ", airportName: "Lakenheath RAF	                 ", country: "United Kingdom", },
    { CityName: "Bristol	         ", code: "BRS", airportName: "Bristol	                        ", country: "United Kingdom", },
    { CityName: "Brize Norton	    ", code: "BZZ", airportName: "Raf Station	                    ", country: "United Kingdom", },
    { CityName: "Burtonwood	      ", code: "BUT", airportName: "Burtonwood	                     ", country: "United Kingdom", },
    { CityName: "Bury St Edmunds	 ", code: "BEQ", airportName: "Honington	                      ", country: "United Kingdom", },
    { CityName: "Cambridge	       ", code: "CBG", airportName: "Cambridge	                      ", country: "United Kingdom", },
    { CityName: "Campbeltown	     ", code: "CAL", airportName: "Machrihanish	                   ", country: "United Kingdom", },
    { CityName: "Cardiff	         ", code: "CWL", airportName: "Cardiff-wales Arpt	             ", country: "United Kingdom", },
    { CityName: "Carlisle	        ", code: "CAX", airportName: "Carlisle	                       ", country: "United Kingdom", },
    { CityName: "Chester	         ", code: "CEG", airportName: "Chester	                        ", country: "United Kingdom", },
    { CityName: "Isle Of Coll	    ", code: "COL", airportName: "Isle Of Coll	                   ", country: "United Kingdom", },
    { CityName: "Isle Of Colonsay	", code: "CSA", airportName: "Isle Of Colonsay	               ", country: "United Kingdom", },
    { CityName: "Coventry	        ", code: "CVT", airportName: "Coventry West Midlands        	 ", country: "United Kingdom", },
    { CityName: "Cromarty	        ", code: "CRN", airportName: "Cromarty	                       ", country: "United Kingdom", },
    { CityName: "Doncaster	       ", code: "DSA", airportName: "Robin Hood International	       ", country: "United Kingdom", },
    { CityName: "Dornoch	         ", code: "DOC", airportName: "Dornoch	                        ", country: "United Kingdom", },
    { CityName: "Dundee	          ", code: "DND", airportName: "Dundee	                         ", country: "United Kingdom", },
    { CityName: "Durham Tees Valle", code: "MME", airportName: "Durham Tees Valley	             ", country: "United Kingdom", },
    { CityName: "Eday	            ", code: "EOI", airportName: "Eday	                           ", country: "United Kingdom", },
    { CityName: "Edinburgh	       ", code: "EDI", airportName: "Turnhouse	                      ", country: "United Kingdom", },
    { CityName: "Enniskillen	     ", code: "ENK", airportName: "Enniskillen	                    ", country: "United Kingdom", },
    { CityName: "Exeter	          ", code: "EXT", airportName: "Exeter	                         ", country: "United Kingdom", },
    { CityName: "Fair Isle	       ", code: "FIE", airportName: "Fair Isle	                      ", country: "United Kingdom", },
    { CityName: "Fairford	        ", code: "FFD", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "Fakenham	        ", code: "FKH", airportName: "Sculthorp RAF	                  ", country: "United Kingdom", },
    { CityName: "Farnborough	     ", code: "FAB", airportName: "Farnborough 	                   ", country: "United Kingdom", },
    { CityName: "Fetlar	          ", code: "FEA", airportName: "Fetlar	                         ", country: "United Kingdom", },
    { CityName: "Filton	          ", code: "FZO", airportName: "Filton	                         ", country: "United Kingdom", },
    { CityName: "Flotta	          ", code: "FLH", airportName: "Flotta	                         ", country: "United Kingdom", },
    { CityName: "Forres	          ", code: "FSS", airportName: "Kinloss	                        ", country: "United Kingdom", },
    { CityName: "Fort William	    ", code: "FWM", airportName: "Heliport	                       ", country: "United Kingdom", },
    { CityName: "Foula	           ", code: "FOA", airportName: "Foula	                          ", country: "United Kingdom", },
    { CityName: "Glasgow	         ", code: "GLA", airportName: "Glasgow International	          ", country: "United Kingdom", },
    { CityName: "Glasgow	         ", code: "PIK", airportName: "Prestwick	                      ", country: "United Kingdom", },
    { CityName: "Glasgow	         ", code: "ZGG", airportName: "ScotRail	                       ", country: "United Kingdom", },
    { CityName: "Gloucester	      ", code: "GLO", airportName: "Gloucestershire	                ", country: "United Kingdom", },
    { CityName: "Grimsby	         ", code: "GSY", airportName: "Binbrook	                       ", country: "United Kingdom", },
    { CityName: "Guernsey	        ", code: "GCI", airportName: "Guernsey	                       ", country: "United Kingdom", },
    { CityName: "Harrogate	       ", code: "HRT", airportName: "Linton-On-Ouse	                 ", country: "United Kingdom", },
    { CityName: "Hatfield	        ", code: "HTF", airportName: "Hatfield	                       ", country: "United Kingdom", },
    { CityName: "Haverfordwest	   ", code: "HAW", airportName: "Haverfordwest	                  ", country: "United Kingdom", },
    { CityName: "Hendon	          ", code: "HEN", airportName: "Hendon	                         ", country: "United Kingdom", },
    { CityName: "High Wycombe	    ", code: "HYC", airportName: "High Wycombe	                   ", country: "United Kingdom", },
    { CityName: "Holyhead	        ", code: "HLY", airportName: "Holyhead	                       ", country: "United Kingdom", },
    { CityName: "Hoy Island	      ", code: "HOY", airportName: "Hoy Island	                     ", country: "United Kingdom", },
    { CityName: "Humberside	      ", code: "HUY", airportName: "Humberside Arpt	                ", country: "United Kingdom", },
    { CityName: "Inverness	       ", code: "INV", airportName: "Inverness	                      ", country: "United Kingdom", },
    { CityName: "Ipswich	         ", code: "IPW", airportName: "Ipswich (Closed)                ", country: "United Kingdom", },
    { CityName: "Islay	           ", code: "ILY", airportName: "Glenegedale	                    ", country: "United Kingdom", },
    { CityName: "Isle Of Skye	    ", code: "SKL", airportName: "Broadford	                      ", country: "United Kingdom", },
    { CityName: "Isle Of Man	     ", code: "IOM", airportName: "Ronaldsway	                     ", country: "United Kingdom", },
    { CityName: "Isles Of Scilly	 ", code: "ISC", airportName: "St Marys	                       ", country: "United Kingdom", },
    { CityName: "Jersey	          ", code: "JER", airportName: "States	                         ", country: "United Kingdom", },
    { CityName: "Kings Lynn	      ", code: "KNF", airportName: "Marham RAF	                     ", country: "United Kingdom", },
    { CityName: "Lands End	       ", code: "LEQ", airportName: "Lands End	                      ", country: "United Kingdom", },
    { CityName: "Leeds	           ", code: "LBA", airportName: "Leeds/Bradford	                 ", country: "United Kingdom", },
    { CityName: "Liverpool	       ", code: "LPL", airportName: "Liverpool John Lennon (Speke)	  ", country: "United Kingdom", },
    { CityName: "Lochgilphead	    ", code: "LPH", airportName: "Heliport	                       ", country: "United Kingdom", },
    { CityName: "Biggin Hill	     ", code: "BQH", airportName: "Biggin Hill	                    ", country: "United Kingdom", },
    { CityName: "London	          ", code: "ZLX", airportName: "British Rail Terminal	          ", country: "United Kingdom", },
    { CityName: "London	          ", code: "LGW", airportName: "Gatwick	                        ", country: "United Kingdom", },
    { CityName: "London	          ", code: "LHR", airportName: "Heathrow	                       ", country: "United Kingdom", },
    { CityName: "London	          ", code: "LCY", airportName: "London City Airport	            ", country: "United Kingdom", },
    { CityName: "London	          ", code: "LTN", airportName: "Luton Airport	                  ", country: "United Kingdom", },
    { CityName: "London	          ", code: "STN", airportName: "Stansted	                       ", country: "United Kingdom", },
    { CityName: "Londonderry	     ", code: "LDY", airportName: "Eglinton (City Of Londonderry)	 ", country: "United Kingdom", },
    { CityName: "Lossiemouth	     ", code: "LMO", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "Lyneham	         ", code: "LYE", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "Manchester	      ", code: "MAN", airportName: "Manchester	                     ", country: "United Kingdom", },
    { CityName: "Manston	         ", code: "MSE", airportName: "Kent International	             ", country: "United Kingdom", },
    { CityName: "Mildenhall	      ", code: "MHZ", airportName: "Mildenhall Arpt	                ", country: "United Kingdom", },
    { CityName: "Mull	            ", code: "ULL", airportName: "Mull	                           ", country: "United Kingdom", },
    { CityName: "Newbury	         ", code: "EWY", airportName: "Greenham RAF	                   ", country: "United Kingdom", },
    { CityName: "Newcastle	       ", code: "NCL", airportName: "Newcastle Airport	              ", country: "United Kingdom", },
    { CityName: "Newquay	         ", code: "NQY", airportName: "St Mawgan	                      ", country: "United Kingdom", },
    { CityName: "North Ronaldsay	 ", code: "NRL", airportName: "North Ronaldsay	                ", country: "United Kingdom", },
    { CityName: "Northampton	     ", code: "ORM", airportName: "Northampton	                    ", country: "United Kingdom", },
    { CityName: "Northolt	        ", code: "NHT", airportName: "Northolt	                       ", country: "United Kingdom", },
    { CityName: "Norwich	         ", code: "NWI", airportName: "Norwich Arpt	                   ", country: "United Kingdom", },
    { CityName: "Nottingham	      ", code: "NQT", airportName: "Nottingham Airport	             ", country: "United Kingdom", },
    { CityName: "Nottingham	      ", code: "EMA", airportName: "Nottingham E. Midlands	         ", country: "United Kingdom", },
    { CityName: "Nottingham	      ", code: "XQI", airportName: "Railway Station	                ", country: "United Kingdom", },
    { CityName: "Nottingham	      ", code: "XQH", airportName: "Railway Station	                ", country: "United Kingdom", },
    { CityName: "Oakham	          ", code: "OKH", airportName: "Cottesmor RAF	                  ", country: "United Kingdom", },
    { CityName: "Oban	            ", code: "OBN", airportName: "Oban Airport	                   ", country: "United Kingdom", },
    { CityName: "Oban	            ", code: "OHP", airportName: "Heliport	                       ", country: "United Kingdom", },
    { CityName: "Odiham	          ", code: "ODH", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "Orkney Island	   ", code: "KOI", airportName: "Orkney Island	                  ", country: "United Kingdom", },
    { CityName: "Outer Skerries	  ", code: "OUK", airportName: "Outer Skerries	                 ", country: "United Kingdom", },
    { CityName: "Oxford	          ", code: "OXF", airportName: "Kidlington	                     ", country: "United Kingdom", },
    { CityName: "Papa Stour	      ", code: "PSV", airportName: "Papa Stour	                     ", country: "United Kingdom", },
    { CityName: "Papa Westray	    ", code: "PPW", airportName: "Papa Westray	                   ", country: "United Kingdom", },
    { CityName: "Penzance	        ", code: "PZE", airportName: "Penzance	                       ", country: "United Kingdom", },
    { CityName: "Perth	           ", code: "PSL", airportName: "Perth	                          ", country: "United Kingdom", },
    { CityName: "Perth	           ", code: "ZXP", airportName: "ScotRail	                       ", country: "United Kingdom", },
    { CityName: "Plymouth	        ", code: "PLH", airportName: "Plymouth	                       ", country: "United Kingdom", },
    { CityName: "Portsmouth	      ", code: "PME", airportName: "Portsmouth	                     ", country: "United Kingdom", },
    { CityName: "Rochester	       ", code: "RCS", airportName: "Rochester	                      ", country: "United Kingdom", },
    { CityName: "Rothesay	        ", code: "RAY", airportName: "Heliport	                       ", country: "United Kingdom", },
    { CityName: "Sanday	          ", code: "NDY", airportName: "Sanday	                         ", country: "United Kingdom", },
    { CityName: "Scampton	        ", code: "SQZ", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "Sheffield	       ", code: "SZD", airportName: "Sheffield City Airport	         ", country: "United Kingdom", },
    { CityName: "Shetland Islands	", code: "LWK", airportName: "Lerwick/Tingwall	               ", country: "United Kingdom", },
    { CityName: "Shetland Islands	", code: "SCS", airportName: "Scatsta	                        ", country: "United Kingdom", },
    { CityName: "Shetland Islands	", code: "LSI", airportName: "Sumburgh	                       ", country: "United Kingdom", },
    { CityName: "Shoreham By Sea	 ", code: "ESH", airportName: "Shoreham	                       ", country: "United Kingdom", },
    { CityName: "Southampton	     ", code: "SOU", airportName: "Eastleigh	                      ", country: "United Kingdom", },
    { CityName: "Southend	        ", code: "SEN", airportName: "London Southend	                ", country: "United Kingdom", },
    { CityName: "St Andrews	      ", code: "ADX", airportName: "Leuchars	                       ", country: "United Kingdom", },
    { CityName: "Stornoway	       ", code: "SYY", airportName: "Stornoway	                      ", country: "United Kingdom", },
    { CityName: "Stronsay	        ", code: "SOY", airportName: "Stronsay	                       ", country: "United Kingdom", },
    { CityName: "Suttonheath	     ", code: "WOB", airportName: "Woodbridge RAF	                 ", country: "United Kingdom", },
    { CityName: "Swansea	         ", code: "SWS", airportName: "Fairwood Comm	                  ", country: "United Kingdom", },
    { CityName: "Swindon	         ", code: "SWI", airportName: "Swindon	                        ", country: "United Kingdom", },
    { CityName: "Swindon	         ", code: "XWS", airportName: "Railway Station	                ", country: "United Kingdom", },
    { CityName: "Tiree	           ", code: "TRE", airportName: "Tiree	                          ", country: "United Kingdom", },
    { CityName: "Unst Shetland Is	", code: "UNT", airportName: "Baltasound	                     ", country: "United Kingdom", },
    { CityName: "Upavon	          ", code: "UPV", airportName: "Upavon	                         ", country: "United Kingdom", },
    { CityName: "Upper Heyford	   ", code: "UHF", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "Waddington	      ", code: "WTN", airportName: "RAF Station	                    ", country: "United Kingdom", },
    { CityName: "West Malling	    ", code: "WEM", airportName: "West Malling	                   ", country: "United Kingdom", },
    { CityName: "Westray	         ", code: "WRY", airportName: "Westray	                        ", country: "United Kingdom", },
    { CityName: "Whalsay	         ", code: "WHS", airportName: "Whalsay	                        ", country: "United Kingdom", },
    { CityName: "Wick	            ", code: "WIC", airportName: "Wick	                           ", country: "United Kingdom", },
    { CityName: "Woodbridge	      ", code: "BWY", airportName: "Bentwaters St	                  ", country: "United Kingdom", },
    { CityName: "Woodford	        ", code: "WFD", airportName: "Woodford	                       ", country: "United Kingdom", },
    { CityName: "Yeovilton	       ", code: "YEO", airportName: "Yeovilton	                      ", country: "United Kingdom", },
];

export default city;